### ISSUE TITLE
Publicar nuevas publicaciones

### ISSUE THREAD

**Issue by cdlopezs02** [DiegoLgr/Practica-Fis#17]
Interfaz: UPublicador
Metodo:publicar() //hay que hacer los de texto y enlace (aunque ahora mismo los tratemos como iguales en la bd)

**Comment by cdlopezs02** [comment]
> En cualquier momento, los usuarios podrán añadir nuevas publicaciones. 

Por tanto la interfaz debe mostrar siempre el boton de añadir publicacion.

**Comment by cdlopezs02** [comment]
Publicar(txt:String): maximo 140 caracteres (la bd no controla el tamaño asi que lo hace el programador de la interfaz o de la logica)

**Comment by cdlopezs02** [comment]
Fran este pa ti. Añade lo de la fecha del sistema el constructor de publicacion pero asegurate de que te lo pone en el mismo formato que la bd.

Luego tienes que hacer los 2 metodos y la query de bd para que lo añada a la base de datos.
Sigue el esquema del metodo crear de la clase gestor de Usuarios

**Comment by Frandccis** [comment]
**DONE**
