### ISSUE TITLE
COSAS QUE FALTAN

### ISSUE THREAD

**Issue by siorata** [DiegoLgr/Practica-Fis#26]
falta un metodo y un comando para recoger un usuario de la base de datos

**Comment by siorata** [comment]
falta un comando para mostrar comentarios

**Comment by ElBarto210** [comment]
En lugar de poner COSAS QUE FALTAN como titulo podrias haber puesto el comentario en su lugar y habria quedado mucho mas claro

**Comment by cdlopezs02** [comment]
> En lugar de poner COSAS QUE FALTAN como titulo podrias haber puesto el comentario en su lugar y habria quedado mucho mas claro

no porque así lo metemos aquí y nos acordamos de meterlo en el uml que sino hacemos el issue y se olvida.

Falta metodo y comando para seguir usuarios.
