### ISSUE TITLE
Ver comentarios publicación propia

### ISSUE THREAD

**Issue by DiegoLgr** [DiegoLgr/Practica-Fis#5]

**Comment by Frandccis** [comment]
PD: No hay interfaz o método para ello

**Comment by Frandccis** [comment]
Interfaz: IPublicación
Método:  ConsultarComentarios

**Comment by Frandccis** [comment]
No existe un controlador asociado ni un comando

**Comment by cdlopezs02** [comment]
Made By @Frandccis
